### PR TITLE
refactor(sankey): update color palette for sankey diagram (composite recipe results)

### PR DESCRIPTION
**Pull request by sjungling**
important to have length of `colors` array match number of nodes

fix https://github.com/moderneinc/moderne-ui/issues/4670

### CODE REVIEW

**Comment by zieka** [comment]
image
🤷🏼 sure I guess; feels like one of those moments where we want to fully control the style and not live in plotly world

**Review by zieka — APPROVED** [review]

**Comment by sjungling** [comment]
I get a much different before and after locally

before
after

**Comment by zieka** [comment]
oh very interesting and based on the change I would expect what you have more than what I had

**Comment by zieka** [comment]
lol just ran it again and now I consistantly get this
image

**Comment by zieka** [comment]
looks like it changes colors each time you restart the kernel

**Comment by sjungling** [comment]
> looks like it changes colors each time you restart the kernel

yeah… just noticed that too… lol wut

**Comment by sjungling** [comment]
but it's using the right colors, best I can see… so :shipit: ❓

**Comment by zieka** [comment]
the plotly colors prop is probably using a random int that is seeded or something

**Pull request merged**
